swagger: "2.0"
info:
  description: "This file contains all REST endpoints exposed by Training Manager."
  version: "1.0.0"
  title: "Training Manager API"
  
host: "localhost:5000"
basePath: "/"
schemes:
  - "http"
  
consumes:
  - "application/json"
produces:
  - "application/json"

tags:
  - name: Feature Group
    description: Feature group related operations
  - name: Pipeline
    description: Pipeline related operations
  - name: Training Job
    description: Training Job related operations

paths:
  /trainingjobs/{trainingjob_name}/{version}:
    get:
      tags:
        - Training Job
      summary: "Fetch training job details by name and version"
      description: "Returns detailed information about a specific training job identified by its name and version."
      parameters:
        - name: "trainingjob_name"
          in: "path"
          required: true
          type: "string"
          description: "Name of the training job"
        - name: "version"
          in: "path"
          required: true
          type: "integer"
          description: "Version of the training job"
      responses:
        200:
          description: "Successful response with training job details"
          schema:
            type: "object"
            properties:
              trainingjob:
                type: "object"
                properties:
                  trainingjob_name:
                    type: "string"
                  description:
                    type: "string"
                  feature_list:
                    type: "string"
                  pipeline_name:
                    type: "string"
                  experiment_name:
                    type: "string"
                  arguments:
                    type: "object"
                  query_filter:
                    type: "string"
                  creation_time:
                    type: "string"
                    format: "date-time"
                  run_id:
                    type: "string"
                  steps_state:
                    type: "object"
                  accuracy:
                    type: "string"
                  enable_versioning:
                    type: "boolean"
                  updation_time:
                    type: "string"
                    format: "date-time"
                  version:
                    type: "integer"
                  pipeline_version:
                    type: "string"
                  datalake_source:
                    type: "string"
                  model_url:
                    type: "string"
                  notification_url:
                    type: "string"
                  is_mme:
                    type: "boolean"
                  model_name:
                    type: "string"
                  model_info:
                    type: "string"
        400:
          description: "Invalid training job name or version"
          schema:
            type: "object"
            properties:
              Exception:
                type: "string"
        404:
          description: "Training job not found"
          schema:
            type: "object"
            properties:
              Exception:
                type: "string"
        500:
          description: "Internal server error"
          schema:
            type: "object"
            properties:
              Exception:
                type: "string"