swagger: "2.0"
info:
  description: "This file contains all REST endpoints exposed by Training Manager."
  version: "1.0.0"
  title: "Training Manager API"
  
host: "localhost:5000"
basePath: "/"
schemes:
  - "http"
  
consumes:
  - "application/json"
produces:
  - "application/json"

tags:
  - name: Feature Group
    description: Feature group related operations
  - name: Pipeline
    description: Pipeline related operations
  - name: Training Job
    description: Training Job related operations